name: Docker Image CD

on:
  workflow_dispatch:
  push:
    branches:
        - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: |
        docker login -u  ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: building
      run: |
        docker build . --compress --tag tartare/tor-relay:master
    - name: pushing
      run: |
        docker push tartare/tor-relay:master

